set -euo pipefail
ROOT=/mnt/c/Users/user/Documents/GitHub
NIXIT="$ROOT/NixIT"; DEP="$ROOT/mdl-infra/deployments"
export SOPS_AGE_KEY_FILE="$DEP/_admin/age-key.txt"
ADMIN_PUB=$(age-keygen -y "$DEP/_admin/age-key.txt")
cd "$NIXIT"
HOSTS="desktop mdl-server svgwdc-svpn-01 svgmdl-keyc-01 svgmdl-kasm-01 svgmdl-forg-01 svgmdl-pape-01 svgmdl-outl-01 svgmdl-immi-01 svgmdl-head-01 svgmdl-exca-01 svgmdl-alia-01 svgmdl-game-01 svgmdl-mood-01 svgmdl-rumi-01 svgmdl-fipa-01 svgmdl-sada-01 svgmdl-devl-01"
sp(){ openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32; }

# strip ALL existing kuze/password* entries from the decrypted file
sops -d secrets/common.yaml | grep -v '^kuze/password' > /tmp/rest.yaml

: > /tmp/kuze.yaml
: > "$DEP/_admin/kuze-passwords.txt"
for h in $HOSTS; do
  pw=$(sp); hash=$(mkpasswd -m sha-512 "$pw")
  echo "kuze/password/$h: \"$hash\"" >> /tmp/kuze.yaml
  echo "$h : $pw" >> "$DEP/_admin/kuze-passwords.txt"
  # Per-host info.md is (re)generated by gen-docs.sh / the SECRETS.md rebuild below;
  # _admin/kuze-passwords.txt is the authoritative list.
done

cat /tmp/kuze.yaml /tmp/rest.yaml > secrets/common.yaml
sops -e -i secrets/common.yaml
rm -f /tmp/kuze.yaml /tmp/rest.yaml

# rebuild master SECRETS.md
{
  echo "# MDL deployments — master secret index (PLAINTEXT, keep private)"
  echo ""
  echo "- admin age pubkey: \`$ADMIN_PUB\`  (private: _admin/age-key.txt)"
  echo "- kuze login passwords: **per-host** (32-char). See \`_admin/kuze-passwords.txt\` and each \`<host>/info.md\`."
  echo ""
  echo "## Per-host kuze passwords"
  echo '```'; cat "$DEP/_admin/kuze-passwords.txt"; echo '```'
  echo ""
  echo "## Per-VM files"
  for h in $HOSTS; do echo "- [$h]($h/info.md)"; done
  echo ""
  echo "## Full decrypted common.yaml"; echo '```yaml'; sops -d secrets/common.yaml; echo '```'
  echo "## Full decrypted ad-dc.yaml"; echo '```yaml'; sops -d secrets/ad-dc.yaml; echo '```'
} > "$DEP/SECRETS.md"

echo "per-host kuze keys in common.yaml: $(sops -d secrets/common.yaml | grep -c '^kuze/password/')"
echo "sample passwords (host : pw):"; head -4 "$DEP/_admin/kuze-passwords.txt"
