set -euo pipefail
ROOT=/mnt/c/Users/user/Documents/GitHub
NIXIT="$ROOT/NixIT"
DEP="$ROOT/mdl-infra/deployments"
mkdir -p "$DEP/_admin"

# ── admin (master) age key ─────────────────────────────────────────────
[ -f "$DEP/_admin/age-key.txt" ] || age-keygen -o "$DEP/_admin/age-key.txt" 2>/dev/null
ADMIN_PUB=$(age-keygen -y "$DEP/_admin/age-key.txt")

HOSTS="desktop mdl-server svgwdc-svpn-01 svgmdl-keyc-01 svgmdl-kasm-01 svgmdl-forg-01 svgmdl-pape-01 svgmdl-outl-01 svgmdl-immi-01 svgmdl-head-01 svgmdl-exca-01 svgmdl-alia-01 svgmdl-game-01 svgmdl-mood-01 svgmdl-rumi-01 svgmdl-fipa-01 svgmdl-sada-01 svgmdl-devl-01"
NEWT_HOSTS="svgmdl-keyc-01 svgmdl-kasm-01 svgmdl-forg-01 svgmdl-pape-01 svgmdl-outl-01 svgmdl-immi-01 svgmdl-head-01 svgmdl-exca-01 svgmdl-alia-01 svgmdl-game-01"

declare -A AGE
for h in $HOSTS; do
  mkdir -p "$DEP/$h"
  [ -f "$DEP/$h/ssh_host_ed25519_key" ] || ssh-keygen -t ed25519 -N "" -C "root@$h" -f "$DEP/$h/ssh_host_ed25519_key" >/dev/null
  AGE[$h]=$(ssh-to-age -i "$DEP/$h/ssh_host_ed25519_key.pub")
done

g(){ openssl rand -hex 32; }
p(){ openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 20; }

# ── generated values (cross-refs reused) ───────────────────────────────
KUZE_PW=$(p); KUZE_HASH=$(mkpasswd -m sha-512 "$KUZE_PW")
KC_DB_PW=$(p); KC_ADMIN_PW=$(p)
FORGEJO_CS=$(g); OUTLINE_CS=$(g); KASM_CS=$(g); IMMICH_CS=$(g); HEADSCALE_CS=$(g); EXCALIDASH_CS=$(g); FREEIPA_CS=$(g)
OUTLINE_SECRET=$(g); OUTLINE_UTILS=$(g)
PAPERLESS_PW=$(p); KASM_PW=$(p)
EXCA_JWT=$(g); EXCA_CSRF=$(g)
MOOD_DB_PW=$(p); MOOD_JWT=$(g)
RUMI_DB_PW=$(p); RUMI_JWT=$(g); RUMI_BOOT_PW=$(p)
FREEIPA_PW=$(p); AD_ADMIN_PW=$(p); CA_PW=$(p)
ADMIN_EMAIL="contact@mydrift.dev"

# ── .sops.yaml with real recipients ────────────────────────────────────
{
  echo "# Auto-generated by scripts/gen-secrets bootstrap. Private keys live in"
  echo "# mdl-infra/deployments/<host>/ssh_host_ed25519_key (+ _admin/age-key.txt)."
  echo "keys:"
  echo "  - &admin $ADMIN_PUB"
  for h in $HOSTS; do echo "  - &$h ${AGE[$h]}"; done
  echo ""
  echo "creation_rules:"
  echo "  - path_regex: secrets/common\.yaml\$"
  echo "    key_groups:"
  echo "      - age:"
  echo "          - *admin"
  for h in $HOSTS; do echo "          - *$h"; done
  echo "  - path_regex: secrets/(ad-dc|radius|mdl-server)\.yaml\$"
  echo "    key_groups:"
  echo "      - age:"
  echo "          - *admin"
  echo "          - *mdl-server"
  echo "          - *svgmdl-sada-01"
} > "$NIXIT/.sops.yaml"

# ── plaintext common.yaml (encrypted below) ────────────────────────────
C="$NIXIT/secrets/common.yaml"
{
  echo "kuze/password: \"$KUZE_HASH\""
  echo "keycloak/env: |"
  echo "  POSTGRES_PASSWORD=$KC_DB_PW"
  echo "  KC_DB_PASSWORD=$KC_DB_PW"
  echo "  KEYCLOAK_ADMIN=admin"
  echo "  KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PW"
  echo "  FORGEJO_CLIENT_SECRET=$FORGEJO_CS"
  echo "  OUTLINE_CLIENT_SECRET=$OUTLINE_CS"
  echo "  KASM_CLIENT_SECRET=$KASM_CS"
  echo "  IMMICH_CLIENT_SECRET=$IMMICH_CS"
  echo "  HEADSCALE_CLIENT_SECRET=$HEADSCALE_CS"
  echo "  EXCALIDASH_CLIENT_SECRET=$EXCALIDASH_CS"
  echo "  FREEIPA_CLIENT_SECRET=$FREEIPA_CS"
  echo "outline/secret-key: \"$OUTLINE_SECRET\""
  echo "outline/utils-secret: \"$OUTLINE_UTILS\""
  echo "outline/oidc-client-secret: \"$OUTLINE_CS\""
  echo "paperless/admin-password: \"$PAPERLESS_PW\""
  echo "kasm/admin-password: \"$KASM_PW\""
  echo "headscale/oidc-client-secret: \"$HEADSCALE_CS\""
  echo "excalidash/env: |"
  echo "  JWT_SECRET=$EXCA_JWT"
  echo "  CSRF_SECRET=$EXCA_CSRF"
  echo "  OIDC_CLIENT_SECRET=$EXCALIDASH_CS"
  echo "moodleng/db-env: |"
  echo "  POSTGRES_PASSWORD=$MOOD_DB_PW"
  echo "moodleng/app-env: |"
  echo "  DATABASE_URL=postgres://moodleng:$MOOD_DB_PW@moodleng-db:5432/moodleng"
  echo "  JWT_SECRET=$MOOD_JWT"
  echo "  OPENAI_API_KEY=REPLACE_WITH_OPENAI_KEY"
  echo "rumi/db-env: |"
  echo "  POSTGRES_PASSWORD=$RUMI_DB_PW"
  echo "rumi/server-env: |"
  echo "  RUMI__DATABASE__URL=postgres://rumi:$RUMI_DB_PW@rumi-db:5432/rumi"
  echo "  RUMI__AUTH__JWT_SECRET=$RUMI_JWT"
  echo "  BOOTSTRAP_EMAIL=$ADMIN_EMAIL"
  echo "  BOOTSTRAP_PASSWORD=$RUMI_BOOT_PW"
  echo "freeipa/env: |"
  echo "  PASSWORD=$FREEIPA_PW"
  echo "fortivpn/config: |"
  echo "  host = REPLACE_FORTIGATE_HOST"
  echo "  port = 443"
  echo "  username = REPLACE"
  echo "  password = REPLACE"
  echo "  trusted-cert = REPLACE"
  echo "  set-dns = 0"
  echo "  pppd-use-peerdns = 0"
  for nh in $NEWT_HOSTS; do
    echo "newt/$nh: |"
    echo "  PANGOLIN_ENDPOINT=https://REPLACE_PANGOLIN"
    echo "  NEWT_ID=REPLACE"
    echo "  NEWT_SECRET=REPLACE"
  done
} > "$C"

# ── plaintext ad-dc.yaml ───────────────────────────────────────────────
A="$NIXIT/secrets/ad-dc.yaml"
{
  echo "ad/admin-password: \"$AD_ADMIN_PW\""
  echo "ca/intermediate-password: \"$CA_PW\""
} > "$A"

# ── encrypt in place (recipients from .sops.yaml) ──────────────────────
cd "$NIXIT"
sops -e -i secrets/common.yaml
sops -e -i secrets/ad-dc.yaml

# ── verify decrypt with admin key ──────────────────────────────────────
export SOPS_AGE_KEY_FILE="$DEP/_admin/age-key.txt"
echo "VERIFY common.yaml keys:"; sops -d secrets/common.yaml | grep -E '^[a-z].*:' | sed 's/:.*/:/' | head -40
echo "VERIFY ad-dc.yaml:"; sops -d secrets/ad-dc.yaml | sed 's/:.*/:/'
echo "ADMIN_PUB=$ADMIN_PUB"
echo "KUZE_PW=$KUZE_PW"  # printed once for the master doc step
